Added Health Check Url

diff --git a/.github/workflows/keep-alive.yml b/.github/workflows/keep-alive.yml
--- a/.github/workflows/keep-alive.yml
+++ b/.github/workflows/keep-alive.yml
@@ -1,1 +1,23 @@
-,l
+name: Keep Services Alive
+
+on:
+  schedule:
+    - cron: "*/3 * * * *"
+
+  workflow_dispatch:
+
+jobs:
+  ping:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Ping all services
+        run: |
+          urls=(
+            "https://url-shortner-q5k2.onrender.com/health"
+          )
+
+          for url in "${urls[@]}"; do
+            echo "Pinging $url"
+            curl --fail --silent --show-error "$url" || echo "Failed: $url"
+          done
